# Generated by Django 5.2.10 on 2026-01-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('target_url', models.URLField(max_length=2048)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
