# Generated by Django 5.2.10 on 2026-01-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=16, unique=True),
        ),
    ]
