# Generated by Django 5.2.10 on 2026-01-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_link_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
